language: node_js
node_js:
   - "4.2.3"

branches:
  only:
    - master

script:
  npm test

after_success:
  - 'cat ./coverage/report-lcov/lcov.info | ./node_modules/.bin/coveralls'

sudo: false

before_install:
  npm install

notifications:
  email: false

addons:
  sauce_connect:true